const sample = {
  student_list: [
    {
      first_name: "Peter",
      last_name: "Fatokun",
      middle_name: "",
      email: "peter34567@gmail.com",
      gender: "Male",
      date_of_birth: "",
      date_of_entry: "",
      parent_email: "",
      parent_phone: "",
      parent_name: "",
      state_of_origin: "",
      lga: "",
      class: "Creche",
      address: "",
      session: 7,
      term: 11,
    },
    {
      first_name: "Temitope",
      last_name: "Adewuyi",
      middle_name: "",
      email: "Temitope34567@gmail.com",
      gender: "Female",
      date_of_birth: "",
      date_of_entry: "",
      parent_email: "",
      parent_phone: "",
      parent_name: "",
      state_of_origin: "",
      lga: "",
      class: "Creche",
      address: "",
      session: 7,
      term: 11,
    },
    {
      first_name: "Bukunmi",
      last_name: "Folarin",
      middle_name: "",
      email: "Bukunmi34567@gmail.com",
      gender: "Female",
      date_of_birth: "",
      date_of_entry: "",
      parent_email: "",
      parent_phone: "",
      parent_name: "",
      state_of_origin: "",
      lga: "",
      class: "Creche",
      address: "",
      session: 7,
      term: 11,
    },
    {
      first_name: "Ajoke",
      last_name: "Fashinat",
      middle_name: "",
      email: "ajoke45678@gmail.com",
      gender: "Female",
      date_of_birth: "",
      date_of_entry: "",
      parent_email: "",
      parent_phone: "",
      parent_name: "",
      state_of_origin: "",
      lga: "",
      class: "Creche",
      address: "",
      session: 7,
      term: 11,
    },
    {
      first_name: "Kudirat",
      last_name: "Kareem",
      middle_name: "",
      email: "Kudirat34567@gmail.com",
      gender: "Female",
      date_of_birth: "",
      date_of_entry: "",
      parent_email: "",
      parent_phone: "",
      parent_name: "",
      state_of_origin: "",
      lga: "",
      class: "Creche",
      address: "",
      session: 7,
      term: 11,
    },
    {
      first_name: "Joy",
      last_name: "nwachukwu",
      middle_name: "",
      email: "Joy34567@gmail.com",
      gender: "Female",
      date_of_birth: "",
      date_of_entry: "",
      parent_email: "",
      parent_phone: "",
      parent_name: "",
      state_of_origin: "",
      lga: "",
      class: "Creche",
      address: "",
      session: 7,
      term: 11,
    },
    {
      first_name: "Elisha",
      last_name: "Awasodor",
      middle_name: "",
      email: "Elisha34567@gmail.com",
      gender: "Female",
      date_of_birth: "",
      date_of_entry: "",
      parent_email: "",
      parent_phone: "",
      parent_name: "",
      state_of_origin: "",
      lga: "",
      class: "Creche",
      address: "",
      session: 7,
      term: 11,
    },
    {
      first_name: "Kehinde",
      last_name: "Steven",
      middle_name: "",
      email: "Kehinde34567@gmail.com",
      gender: "Female",
      date_of_birth: "",
      date_of_entry: "",
      parent_email: "",
      parent_phone: "",
      parent_name: "",
      state_of_origin: "",
      lga: "",
      class: "Creche",
      address: "",
      session: 7,
      term: 11,
    },
    {
      first_name: "Alihat",
      last_name: "Kareem",
      middle_name: "",
      email: "Alihat34567@gmail.com",
      gender: "Female",
      date_of_birth: "",
      date_of_entry: "",
      parent_email: "",
      parent_phone: "",
      parent_name: "",
      state_of_origin: "",
      lga: "",
      class: "Creche",
      address: "",
      session: 7,
      term: 11,
    },
  ],
};
